### ISSUE TITLE
Make a clear plan for Beaker parameter exploration.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#595]

**Comment by schmmd** [comment]
I don't exactly have a clear plan, but I learned a lot about the different options available in Beaker.  Most of them don't work because AllenNLP cannot interpret environment variables as non-strings and because Beaker functionality is missing some necessary components.

On the AllenNLP side, I think we should close out the easy parts of https://github.com/allenai/allennlp/issues/447 and add overrides.  On the Beaker side, they prefer coming up with an easier way to specify experiments on the command line.

Here are some notes about different potential approaches.

```
Methods of doing a parameter search with AllenNLP and Beaker:

* Manually run a series of experiments and aggregate the results.

This is what Tushar does presently.  This has full flexibility but requires
manually aggregating the results.

* Create a batched experiment and manually create permutations of the configuration.

Pro's: nice Beaker visualization and fine-grained control.
Con's: labor intensive to create each dataset, does not scale to hundreds of permutations.

http://beaker.allenai.org/ex/ex_8dm8xov2wj7v

description: "Example wordcount experiment"
tasks:
  - name: snli2
    spec:
      description: Train SNLI with 2 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: '/output'
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: ds_w0e4m4zphjxm
          containerPath: /config.json

  - name: snli3
    spec:
      description: Train SNLI with 3 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: /output
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: ds_qy9voivhii0v
          containerPath: /config.json

  - name: snli4
    spec:
      description: Train SNLI with 4 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: /output
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: ds_3cnl9qmexud8
          containerPath: /config.json

* Create a batched experiment and create permutations with overrides.

pro: nice Beaker visualization and fine-grained control.
pro: a single dataset can be used for every configuration.
con: you still need to create a big yaml file that largely just repeats itself.
con: overrides isn't impelmented on train (but easily could be, see https://github.com/allenai/allennlp/pull/402)

description: "Example wordcount experiment"
tasks:
  - name: snli2
    spec:
      description: Train SNLI with 2 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: '/output'
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
        - --overrides '{ "trainer.num_epochs": 4 }'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: XYZ
          containerPath: /config.json

  - name: snli3
    spec:
      description: Train SNLI with 3 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: /output
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
        - --overrides '{ "trainer.num_epochs": 4 }'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: XYZ
          containerPath: /config.json

  - name: snli4
    spec:
      description: Train SNLI with 4 epochs
      image: allennlp/allennlp:v0.3.0
      resultPath: /output
      args:
        - 'allennlp/run'
        - 'train'
        - '/config.json'
        - '-s'
        - '/output'
        - --overrides '{ "trainer.num_epochs": 4 }'
      datasetMounts:
        - datasetId: snli_1_train_short.1
          containerPath: /training.jsonl
        - datasetId: XYZ
          containerPath: /config.json

* Grid search

Con's: cannot specify the arguments I need so I would need to create a custom Docker image.
Con's: limiting and custom configuration language for setting up searches.
Con's: AllenNLP does not support training overrides.  Overrides are needed because otherwise environment variables are interpreted as strings.
Pro's: compact representation.

{
  "envs": [
    {
      "name": "EPOCHS",
      "range": {"start": 2, "step": 1, "end": 4}
    }
  ]
}

(inside Docker image set run command to the following)

python -m allennlp.run train /config.json -s /output --overrides "{ \"trainer.num_epochs\": $EPOCHS }'

* Manually create an experiment group

Con's: AllenNLP does not support training overrides.  Overrides are needed because otherwise environment variables are interpreted as strings.

beaker group create snli_epoch
for EPOCH in {2..4}
do
    EX=$(beaker experiment run --result-path /output --gpu-count=1 --source XYZ:/config.json --detach allennlp/allennlp:v0.3.0 allennlp/run train /config.json -s /output --overrides '{ "trainer.num_epochs": $EPOCH}')
    beaker group add snli_epoch $EX
done
```
